/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    screens: {
      poke_xl: "1600px",
      poke_data: "1350px",
      poke_l: "1200px",
      tablet: "1024px",
      tablet_s: "768px",
      mobile: "500px",
      pokedex_1: "600px",
    },
    extend: {
      fontFamily: {
        pokefont: ["Pokefont", "sans-serif"],
        code: ["Code", "sans-serif"],
      },
      backgroundImage: {
        pattern: "url('images/body_bg.png')",
        menu: "url('images/menu_bg.svg')",
        menu_dark: "url('images/menu_bg_w.svg')",
        menu_sm: "url('images/menu_bg_sm.svg')",
        menu_dark_sm: "url('images/menu_bg_sm_w.svg')",
      },
      colors: {
        bug: "#729f3f",
        dark: "#161616",
        dragon: "#bb9f1e",
        electric: "#ead02a",
        fairy: "#fdb9e9",
        fighting: "#c42312",
        fire: "#fd7d24",
        flying: "#a3deeb",
        ghost: "#7b62a3",
        grass: "#50cc8a",
        ground: "#807c60",
        ice: "#51c4e7",
        normal: "#f3f3f3",
        poison: "#b97fc9",
        psyhic: "#f366b9",
        rock: "#493d07",
        steel: "#9aaaab",
        water: "#4592c1",
        pokedex: "#194485",
        pokefigt: "#e51b1b",
        pokecreator: "#67a814",
        pokeleader: "#c8981b ",
        elementbBg: "#2b2b2b",
        elementbBg_w: "#b7b7b7",
        pokemonBg: "#373737",
        bgColor: "#cbcbcb",
      },
      boxShadow: {
        shadow: "5px 5px 8px rgba(0, 0, 0, 0.5)",
        shadow_w: "5px 5px 8px rgba(0, 0, 0, 0.2)",
      },
      keyframes: {
        landingPage: {
          "0%, 65%": { opacity: "0" },
          "35%, 100%": { opacity: "1" },
        },
        welcomme: {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        input_name: {
          "0%": {
            opacity: "0",
            transform: "translateY(-500px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0px)",
          },
        },
        appear: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        grow: {
          "0%": { width: "0%" },
          "100%": { width: "100%" },
        },
        ping: {
          // "50%": { filter: "brightness(125%)" },
          // "100%": { filter: "brightness(100%)" },
          "50%": { transform: "scale(1.2)" },
          "100%": { transform: "scale(1)" },
        },
        comic: {
          "0%": { opacity: "0" },
          "20%": {
            opacity: "1",
            transform: "scale(1)",
          },
          "40%": { transform: "scale(1.2)" },
          "60%": { transform: "scale(1.2)" },
          "80%": {
            transform: "scale(1)",
            opacity: "1",
          },
          "100%": { opacity: "0" },
        },
        hit: {
          "0%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(20px)" },
          "40%": { transform: "translateY(-20px)" },
          "60%": { transform: "translateX(-100px)" },
        },
      },
      animation: {
        landingPage: "landingPage 1.5s 2s 2 ease-in-out forwards",
        welcomme: "welcomme 1s 1s ease-in-out forwards",
        input_name: "input_name 1s 5s ease-in-out forwards",
        appear: "appear 300ms ease-out both",
        grow: "grow 400ms ease-out both",
        ping: "ping 300ms linear forwards",
        comic: "comic 2s linear forwards",
        hit: "hit 650ms linear forwards",
      },
    },
  },
  plugins: [],
};
